"""create_members_table

Revision ID: 3c3fb1d4fbad
Revises: 7aa60b9cb17a
Create Date: 2025-10-15 11:41:58.169068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c3fb1d4fbad"
down_revision: Union[str, Sequence[str], None] = "7aa60b9cb17a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("name", name=op.f("uq_locations_name")),
        schema="cqu_schema",
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
        schema="cqu_schema",
    )
    op.create_table(
        "members",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("linkedin", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("location_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["cqu_schema.locations.id"],
            name=op.f("fk_members_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["cqu_schema.roles.id"],
            name=op.f("fk_members_role_id_roles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("email", name=op.f("uq_members_email")),
        schema="cqu_schema",
    )
    op.drop_constraint(
        op.f("fk_projects_category_id_project_categories"),
        "projects",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_projects_category_id_project_categories"),
        "projects",
        "project_categories",
        ["category_id"],
        ["id"],
        source_schema="cqu_schema",
        referent_schema="cqu_schema",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_category_id_project_categories"),
        "projects",
        schema="cqu_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_projects_category_id_project_categories"),
        "projects",
        "project_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_table("members", schema="cqu_schema")
    op.drop_table("roles", schema="cqu_schema")
    op.drop_table("locations", schema="cqu_schema")
    # ### end Alembic commands ###
