"""create_events_migrations

Revision ID: c40c97060fc5
Revises: 1f8e78c23301
Create Date: 2025-10-22 09:21:06.994458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c40c97060fc5"
down_revision: Union[str, Sequence[str], None] = "1f8e78c23301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_datetime", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("thumbnail", sa.String(), nullable=True),
        sa.Column(
            "is_online", sa.Boolean(), server_default=sa.text("False"), nullable=False
        ),
        sa.Column("recurrence", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "event_datetime", "title", name=op.f("uq_events_event_datetime")
        ),
        schema="cqu_schema",
    )
    op.create_table(
        "campus_events",
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("campus_id", sa.BigInteger(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["cqu_schema.campuses.id"],
            name=op.f("fk_campus_events_campus_id_campuses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["cqu_schema.events.id"],
            name=op.f("fk_campus_events_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "campus_id", name=op.f("pk_campus_events")),
        schema="cqu_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("campus_events", schema="cqu_schema")
    op.drop_table("events", schema="cqu_schema")
    # ### end Alembic commands ###
