"""create_blogs_migrations

Revision ID: e5b3f0b2b717
Revises: c40c97060fc5
Create Date: 2025-10-23 00:05:25.315311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5b3f0b2b717"
down_revision: Union[str, Sequence[str], None] = "c40c97060fc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("publish_date", sa.Date(), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blogs")),
        sa.UniqueConstraint("title", name=op.f("uq_blogs_title")),
        schema="cqu_schema",
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
        schema="cqu_schema",
    )
    op.create_table(
        "blog_tags",
        sa.Column("blog_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["cqu_schema.blogs.id"],
            name=op.f("fk_blog_tags_blog_id_blogs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["cqu_schema.tags.id"], name=op.f("fk_blog_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("blog_id", "tag_id", name=op.f("pk_blog_tags")),
        schema="cqu_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_tags", schema="cqu_schema")
    op.drop_table("tags", schema="cqu_schema")
    op.drop_table("blogs", schema="cqu_schema")
    # ### end Alembic commands ###
